version: '3.9'

services:
  redis-pubsub:
    restart: unless-stopped
    image: redis:latest
    container_name: redis-pubsub
    hostname: redis-pubsub
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
